### ISSUE TITLE
ImportError: No module named requests

### ISSUE THREAD

**Issue by mictadlo** [TAMU-CPT/galaxy-apollo#7]
Hi @erasche,
I just installed Apollo on Galaxy 15.07 and after I run `WA2: Register Account` I received the following error:
 
_Fatal error: Exit code 1 ()
Traceback (most recent call last):
  File "/mnt/galaxy/shed_tools/testtoolshed.g2.bx.psu.edu/repos/eric-rasche/apollo/c8e16c8eff98/apollo/create_account.py", line 5, in <module>
    from webapollo import WebApolloInstance, GroupObj
  File "/mnt/galaxy/shed_tools/testtoolshed.g2.bx.psu.edu/repos/eric-rasche/apollo/c8e16c8eff98/apollo/webapollo.py", line 1, in <module>
    import requests
ImportError: No module named requests_

What did I do wrong and to which Apollo server does it try to register?

Thank you in advance.

Mic

**Comment by erasche** [comment]
Hi @mictadlo 

1. these tools do not have any idea of dependencies. You will need to in some way install requests into galaxy's virtual environment. (Something like `/mnt/galaxy/.venv/bin/activate && pip install requests` probably)
  - Since this tool suite is not finalised yet, that is the reason for this inconvenience. There is a big feature I need to implement on the Galaxy side before these tools are more generally useful.
  - Additionally you may consider manually installing this repository (e.g. `git clone` into your galaxy tools directory), if the one in the shed reads "WA2" then it is extremely out of date). We currently do this for the docker images.
2. Your galaxy version is quite old. This tool suite may use features that are not supported in your version of Galaxy.

**Comment by mictadlo** [comment]
Thank you for the response. By any chance, do you know which Galaxy version will be supported?

**Comment by erasche** [comment]
@mictadlo I do not have a minimum required version, I'm not seeing any really fancy features being used here, right now. Future versions of this tool will need some newer galaxy features once they're implemented in galaxy. For now, this should work fine for you, I believe.

**Comment by mictadlo** [comment]
I tried 
_$ pip install requests
Requirement already satisfied (use --upgrade to upgrade): requests in /usr/local/lib/python2.7/dist-packages_

Did I miss anything?

**Comment by erasche** [comment]
Galaxy jobs currently run in galaxy's virtual environment (I believe), so you'd need to activate that first if you didn't.

**Comment by mictadlo** [comment]
i did the following and still not luck:

_~/galaxy-app/.venv/bin$ sh activate
~/galaxy-app/.venv/bin$ pip install requests
Requirement already satisfied (use --upgrade to upgrade): requests in /usr/local/lib/python2.7/dist-packages_

Be

**Comment by erasche** [comment]
If you're willing to try, I believe that installing the tools locally (e.g. in `$GALAXY/tools/apollo` or similar) might then solve the problem. If I had to guess, Galaxy handles dependencies differently for shed installed tools.

Again, this will all be fixed at some point in the future.

**Comment by nathandunn** [comment]
I had to do this from the above directory:

    ./venv/bin/activate
    
Before running.  However, I think you might also have to update the ```requirements.txt```, though I know there is a better way to do it:

```
requirements.txt -> lib/galaxy/dependencies/pinned-requirements.txt
ndunn:galaxy% git diff
diff --git a/lib/galaxy/dependencies/pinned-requirements.txt b/lib/galaxy/dependencies/pinned-requirements.txt
index 52a22ed..5478836 100644
--- a/lib/galaxy/dependencies/pinned-requirements.txt
+++ b/lib/galaxy/dependencies/pinned-requirements.txt
@@ -68,3 +68,6 @@ ecdsa==0.13
 # Flexible BAM index naming
 pysam==0.8.4+gx1
 
+# add additional requirements 
+bcbio-gff==0.6.2
+biopython==1.67
```

Now I am getting this error:

```
Fatal error: Exit code 2 ()
usage: list_organisms.py [-h] [--remote_user REMOTE_USER]
                         apollo username password
list_organisms.py: error: too few arguments
```

But no additional requirements errors.

**Comment by erasche** [comment]
18. jul. 2016 2.44 p.m. skrev "Nathan Dunn" <notifications@github.com>:
>
> I had to do this from the above directory:
>
> ./venv/bin/activate

Depends on where your venv. Instructions from other comment use the galaxy
venv, your's.may be different.

>
> Before running. However, I think you might also have to update the
requirements.txt, though I know there is a better way to do it:

Yes, unfoetunately that is "wait until the galaxy portions are done" ;)

>
> requirements.txt -> lib/galaxy/dependencies/pinned-requirements.txt
ndunn:galaxy% git diff diff --git
a/lib/galaxy/dependencies/pinned-requirements.txt
b/lib/galaxy/dependencies/pinned-requirements.txt index 52a22ed..5478836
100644 --- a/lib/galaxy/dependencies/pinned-requirements.txt +++
b/lib/galaxy/dependencies/pinned-requirements.txt @@ -68,3 +68,6 @@
ecdsa==0.13 # Flexible BAM index naming pysam==0.8.4+gx1 +# add additional
requirements +bcbio-gff==0.6.2 +biopython==1.67

Would recommend against adding to.requirements, it will possibly make your
life less pleasant during upgrades.

>
> Now I am getting this error:
>
> Fatal error: Exit code 2 () usage: list_organisms.py [-h] [--remote_user
REMOTE_USER] apollo username password list_organisms.py: error: too few
arguments

This is usually due to missing environment variables. You'll need to ensure
these are set but that's different for every galaxy deployment method. How
are you deploying galaxy currently?

**Comment by nathandunn** [comment]
@erasche   

WRT to the REMOTE_USER I'm not running a galaxy currently.    

WRT to the .venv, I meant to imply that I'm using the galaxy .venv (looking back at my comment, guess that was not obvious).     I would definitely not advocate using the pinned requirements, either, but might be a useful test to make sure all the requirements for the tools can be properly loaded.   I remember this being a bear, as well.
